#!/usr/bin/env python3
"""Convert a tb_worlds (turtlebot-maze) Harmonic port of an AWS RoboMaker world into a ubot
benchmark world xacro.

Keeps the furniture/building <model> blocks (forced static) and the indoor <light> blocks, drops the source's
own systems / physics / scene / ground / sun (the shared ubot macros replace them) and the roof
(it blocks the overhead view and never touches a 2D sensor). Indoor lights are wrapped so the
low-light condition can switch them off.

Usage: import_aws_world.py SRC.sdf.xacro OUT.sdf.xacro WORLD_NAME
Condition geometry (glass, walkers) is not part of the world file: it is read from
missions/<WORLD_NAME>.yaml at render time.
"""
import re
import sys

HEADER = """<?xml version="1.0"?>
<!--
  {name}: ubot benchmark world, generated by ubot_worlds/scripts/import_aws_world.py.
  Furniture and building layout from the AWS RoboMaker worlds (aws-robotics, MIT-0) as ported
  to Gazebo Harmonic in github.com/zp78-ship-it/turtlebot-maze tb_worlds (MIT). Do not edit the
  generated sections by hand; re-run the script. Glass/walkers come from missions/{name}.yaml.

  Args: condition = nominal | glass | dynamic | degraded | low_light
-->
<sdf version="1.9" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:arg name="condition" default="nominal"/>
  <xacro:arg name="physics" default="dartsim"/>
  <xacro:property name="condition" value="$(arg condition)"/>
  <xacro:include filename="$(find ubot_worlds)/worlds/include/ubot_world_common.xacro"/>
  <world name="{name}">
    <xacro:ubot_world_systems engine="$(arg physics)"/>
    <xacro:ubot_world_lighting low_light="${{condition == 'low_light'}}"/>
    <xacro:ubot_ground_plane/>
    <!-- C1 glass / C2 walkers: placements live in missions/{name}.yaml -->
    <xacro:ubot_condition_geometry world="{name}" condition="${{condition}}"/>

"""

FOOTER = "  </world>\n</sdf>\n"


def blocks(text, tag):
    """Top-level <tag name=...>...</tag> blocks inside the world, in order."""
    return re.findall(rf"<{tag}\s+name=['\"][^'\"]+['\"].*?</{tag}>", text, flags=re.S)


def main():
    src, out, name = sys.argv[1:4]
    text = open(src).read()
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)          # drop comments (incl. broken ones)
    models = [m for m in blocks(text, "model")
              if "Roof" not in m and "ground_plane" not in m]
    # Furniture never moves in the benchmark. The wrapper <static> does not reach the included
    # model, and ~40% of the AWS models are non-static with mesh collisions resting on the floor,
    # which drops the house to ~0.03x real time. <include><static> overrides it.
    models = [re.sub(r"<include>(?!\s*<static>)", "<include><static>true</static>", m) for m in models]
    lights = [lt for lt in blocks(text, "light") if not re.match(r"<light\s+name=['\"]sun['\"]", lt)]
    with open(out, "w") as f:
        f.write(HEADER.format(name=name))
        f.write(f"    <!-- {len(models)} static models -->\n")
        for m in models:
            f.write("    " + m.strip() + "\n\n")
        f.write(f"    <!-- {len(lights)} indoor lights, off in low_light -->\n")
        f.write("    <xacro:unless value=\"${condition == 'low_light'}\">\n")
        for lt in lights:
            f.write("    " + lt.strip() + "\n")
        f.write("    </xacro:unless>\n")
        f.write(FOOTER)
    print(f"{out}: {len(models)} models, {len(lights)} lights")


if __name__ == "__main__":
    main()
