"""make_missions: generate the mapping route and navigation goals of a world from its
ground-truth map. Deterministic for a given map and seed (PROTOCOL.md, "Missions").

Definitions (all on the ground-truth traversability grid, 8-connected, 5 cm cells):
  feasible   free cells with clearance >= ROBOT_RADIUS (0.25 m), connected to the spawn; the
             C1 glass panes are burned in as obstacles so missions are identical in every condition
  goals      K goals by geodesic farthest-point sampling among feasible cells with clearance
             >= goal_clearance, starting from the spawn; visited in sampling order, so every leg
             is long. Goal headings are drawn uniformly from the seed.
  route      coverage waypoints by geodesic farthest-point sampling until the largest remaining
             gap is < route_spacing, toured greedily (nearest unvisited next) from the spawn and
             back to it (a loop closure), joined by shortest paths that prefer high clearance,
             planned on cells with >= 0.30 m clearance, straightened locally (segments keep
             >= 0.35 m clearance and stay within 0.25 m of the grid path), and resampled
             every 0.10 m.

Writes a '# ---- generated' block at the end of ubot_worlds/missions/<world>.yaml (the hand-written
part above it is kept) and a PNG preview next to it.

Usage: ros2 run ubot_bench make_missions --world small_house [--goals 8] [--seed 1]
"""
import argparse
import math
import os

import numpy as np
import yaml

from ubot_bench.grid import Grid, burn_glass
from ubot_bench.planning import (ROBOT_RADIUS, clearance_field, dijkstra, nearest_feasible,
                                 path_to)

DEFAULTS = {
    # world: (goals, goal_clearance, route_spacing)
    'arena_5x5': (6, 0.35, 1.2),
    'small_house': (8, 0.45, 3.0),
    'bookstore': (8, 0.45, 3.0),
    'small_warehouse': (8, 0.45, 5.0),   # open space: LiDARs see far, wider coverage spacing
}
MARK = '# ---- generated by ubot_bench make_missions: do not edit below this line ----'
# The mapping route needs more room than a goal: pure pursuit cuts corners and, in an in-place
# turn, the chassis swings about the front axle (rear corners sweep ~0.33 m around it).
ROUTE_PLAN_CLEARANCE = 0.30     # m, cells the route may use
ROUTE_STRAIGHT_CLEARANCE = 0.35 # m, straight segments after pulling


def src_dir():
    return os.path.expanduser('~/uni-bot/src/ubot/ubot_worlds')


def farthest_points(passable, start, candidates, k=None, min_gap=None):
    """Geodesic FPS from start over candidate cells. Returns [(r, c)] in sampling order."""
    chosen = []
    dist, _ = dijkstra(passable, [start])
    while True:
        d = np.where(candidates, dist, -np.inf)
        i = int(np.argmax(d))
        best = d.flat[i]
        if not np.isfinite(best) or best <= 0:
            break
        if min_gap is not None and best < min_gap:
            break
        cell = divmod(i, passable.shape[1])
        chosen.append(cell)
        if k is not None and len(chosen) >= k:
            break
        dnew, _ = dijkstra(passable, [cell])
        dist = np.minimum(dist, dnew)
    return chosen


def tour(passable, start, cells):
    """Greedy nearest-neighbour order by geodesic distance, starting at start."""
    order, cur, left = [], start, list(cells)
    while left:
        dist, _ = dijkstra(passable, [cur], targets=left)
        j = int(np.argmin([dist[r, c] for r, c in left]))
        cur = left.pop(j)
        order.append(cur)
    return order


def segment_clear(a, b, clear, res, min_clear):
    """True if every point of the straight segment a->b (cells) has clearance >= min_clear."""
    n = int(max(abs(b[0] - a[0]), abs(b[1] - a[1])) * 2) + 1
    r = np.rint(np.linspace(a[0], b[0], n)).astype(int)
    c = np.rint(np.linspace(a[1], b[1], n)).astype(int)
    return bool(np.all(clear[r, c] >= min_clear))


def string_pull(cells, clear, res, min_clear, max_dev=0.25):
    """Straighten a grid path locally: from each vertex, extend a straight segment forward along
    the path for as long as (a) the segment keeps >= min_clear clearance and (b) every skipped path
    cell stays within max_dev (m) of the segment. Stops at the first violation, so it removes the
    8-connected zig-zag without ever skipping a loop of the tour."""
    pts = np.asarray(cells, dtype=float)
    out, i, n = [cells[0]], 0, len(cells)
    while i < n - 1:
        j = i + 1
        for k in range(i + 2, n):
            if not segment_clear(cells[i], cells[k], clear, res, min_clear):
                break
            a, b = pts[i], pts[k]
            ab = b - a
            L = np.hypot(*ab)
            if L < 1e-9:
                break
            mid = pts[i + 1:k]
            dev = np.abs(ab[0] * (mid[:, 1] - a[1]) - ab[1] * (mid[:, 0] - a[0])) / L
            if dev.max() * res > max_dev:
                break
            j = k
        out.append(cells[j])
        i = j
    return out


def resample(xy, step=0.10):
    xy = np.asarray(xy, dtype=float)
    seg = np.linalg.norm(np.diff(xy, axis=0), axis=1)
    s = np.concatenate([[0.0], np.cumsum(seg)])
    t = np.append(np.arange(0.0, s[-1], step), s[-1])
    return np.stack([np.interp(t, s, xy[:, 0]), np.interp(t, s, xy[:, 1])], axis=1), float(s[-1])


def smooth_resample(xy, step=0.10, window=7):
    xy = np.asarray(xy, dtype=float)
    if len(xy) > window:
        k = np.ones(window) / window
        pad = window // 2
        sm = np.stack([np.convolve(np.pad(xy[:, i], pad, mode='edge'), k, mode='valid')
                       for i in range(2)], axis=1)
        sm[0], sm[-1] = xy[0], xy[-1]
        xy = sm
    seg = np.linalg.norm(np.diff(xy, axis=0), axis=1)
    s = np.concatenate([[0.0], np.cumsum(seg)])
    t = np.arange(0.0, s[-1], step)
    t = np.append(t, s[-1])
    return np.stack([np.interp(t, s, xy[:, 0]), np.interp(t, s, xy[:, 1])], axis=1), float(s[-1])


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--world', required=True)
    ap.add_argument('--goals', type=int)
    ap.add_argument('--seed', type=int, default=1)
    a = ap.parse_args()
    k, goal_clear, spacing = DEFAULTS[a.world]
    k = a.goals or k

    mpath = os.path.join(src_dir(), 'missions', f'{a.world}.yaml')
    text = open(mpath).read().split(MARK)[0].rstrip() + '\n'
    mission = yaml.safe_load(text)
    # Traversability map (union of the 0.08 / 0.22 / 0.36 m slices): what physically stops the robot.
    grid = Grid.load(os.path.join(src_dir(), 'maps_gt', f'{a.world}_traversable.yaml'))
    # Plan around the glass panes in every condition: the route and goals must stay valid (and
    # identical) whether or not the panes are present.
    grid = burn_glass(grid, mission.get('conditions', {}).get('glass'))
    clear = clearance_field(grid)
    xmin, xmax, ymin, ymax = mission['bounds']
    rows, cols = np.indices(grid.shape)
    wx, wy = grid.cell_to_world(rows, cols)
    in_bounds = (wx >= xmin) & (wx <= xmax) & (wy >= ymin) & (wy <= ymax)
    feasible = (clear >= ROBOT_RADIUS) & in_bounds
    sx, sy = mission['spawn']['x'], mission['spawn']['y']
    start = nearest_feasible(grid, feasible, sx, sy)
    if start is None:
        raise SystemExit(f'spawn ({sx}, {sy}) is not within 0.5 m of feasible space')
    reach, _ = dijkstra(feasible, [start])
    feasible &= np.isfinite(reach)

    # Goals
    cand = feasible & (clear >= goal_clear)
    goal_cells = farthest_points(feasible, start, cand, k=k)
    rng = np.random.default_rng(a.seed)
    goals = []
    for r, c in goal_cells:
        x, y = grid.cell_to_world(r, c)
        goals.append([round(float(x), 2), round(float(y), 2),
                      round(float(rng.uniform(-math.pi, math.pi)), 3)])

    # Mapping route: coverage points, greedy tour, return to spawn.
    spacing_cells = spacing / grid.res
    cover = farthest_points(feasible, start, feasible & (clear >= ROUTE_PLAN_CLEARANCE + 0.05),
                            min_gap=spacing_cells)
    order = tour(feasible, start, cover) + [start]
    cost = 1.0 + 0.15 / np.maximum(clear, 0.05)           # prefer the middle of passages
    route_ok = feasible & (clear >= ROUTE_PLAN_CLEARANCE)
    route_ok &= np.isfinite(dijkstra(route_ok, [start])[0])
    order = [c for c in order if route_ok[c]] + ([start] if order[-1] == start else [])
    pts, cur = [], start
    for nxt in order:
        _, parent = dijkstra(route_ok, [cur], cost=cost, targets=[nxt])
        seg = path_to(parent, grid.shape, nxt)
        pts.extend(seg if not pts else seg[1:])
        cur = nxt
    pulled = string_pull(pts, clear, grid.res, ROUTE_STRAIGHT_CLEARANCE)
    wxy = np.stack(grid.cell_to_world(np.array([p[0] for p in pulled]),
                                      np.array([p[1] for p in pulled])), axis=1)
    route, length = resample(wxy)

    gen = {
        'generated': {'seed': a.seed, 'goals': k, 'goal_clearance': goal_clear,
                      'route_spacing': spacing, 'robot_radius': ROBOT_RADIUS,
                      'route_clearance': [ROUTE_PLAN_CLEARANCE, ROUTE_STRAIGHT_CLEARANCE],
                      'route_length_m': round(length, 1), 'route_waypoints': len(cover),
                      'feasible_m2': round(float(feasible.sum()) * grid.res ** 2, 1)},
        'goals': goals,
        'mapping_route': [[round(float(x), 3), round(float(y), 3)] for x, y in route],
    }
    with open(mpath, 'w') as f:
        f.write(text + '\n' + MARK + '\n')
        yaml.safe_dump(gen, f, default_flow_style=None, sort_keys=False, width=100)
    preview(grid, feasible, goals, route, (sx, sy), os.path.join(src_dir(), 'missions',
                                                                 f'{a.world}.png'))
    print(f'{a.world}: {len(goals)} goals, route {length:.1f} m through {len(cover)} waypoints, '
          f'feasible {gen["generated"]["feasible_m2"]} m2')
    print('REBUILD ubot_worlds before running experiments (it installs copies of missions/).')


def preview(grid, feasible, goals, route, spawn, path):
    from PIL import Image, ImageDraw
    s = max(1, int(800 / max(grid.shape)))
    img = np.full(grid.shape + (3,), 200, np.uint8)
    img[grid.data == 0] = 255
    img[feasible] = (225, 240, 225)
    img[grid.data == 100] = 0
    im = Image.fromarray(img).resize((grid.shape[1] * s, grid.shape[0] * s), Image.NEAREST)
    d = ImageDraw.Draw(im)

    def px(x, y):
        r, c = grid.world_to_cell(x, y)
        return (int(c) * s + s // 2, int(r) * s + s // 2)
    d.line([px(x, y) for x, y in route], fill=(40, 110, 210), width=max(1, s // 2))
    for i, (x, y, yaw) in enumerate(goals):
        p = px(x, y)
        d.ellipse([p[0] - 3 * s, p[1] - 3 * s, p[0] + 3 * s, p[1] + 3 * s], fill=(220, 70, 40))
        q = px(x + 0.4 * math.cos(yaw), y + 0.4 * math.sin(yaw))
        d.line([p, q], fill=(220, 70, 40), width=max(1, s // 2))
        d.text((p[0] + 4 * s, p[1] - 4 * s), f'G{i + 1}', fill=(0, 0, 0))
    p = px(*spawn)
    d.rectangle([p[0] - 3 * s, p[1] - 3 * s, p[0] + 3 * s, p[1] + 3 * s], fill=(20, 150, 60))
    im.save(path)


if __name__ == '__main__':
    main()
